site_name: 自动化知识笔记
site_url: https://huarenjian1.github.io/
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
